const ADD_FAVORITE = 'ADD_FAVORITE'
const REMOVE_FAVORITE = 'REMOVE_FAVORITES'
const FIlTER_FAVORITE = 'FILTER_FAVORITES'
const ORDER_CARDS = 'ORDER_CARDS'

export {ADD_FAVORITE, REMOVE_FAVORITE, FIlTER_FAVORITE, ORDER_CARDS}